
services:
  anaconda:
    image: mcr.microsoft.com/vscode/devcontainers/anaconda:0-3
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    networks:
      - montes_network

  jupyter:
    image: jupyter/scipy-notebook
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ../jupyter_path:/home/jovyan
    networks:
      - montes_network

  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ../postgres_path:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - montes_network

  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ~/.ollama:/root/.ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - montes_network

networks:
  montes_network:
